/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;

import app.Elements.HostItem;
import app.Elements.HostTable;
import app.Elements.SimulatorItem;
import java.math.BigDecimal;
import java.util.List;
import material.graphs.Vertex;
import objects.Node;
import app.Elements.NodeItem;

/**
 *
 * @author alber
 */
public class VAddPackage extends javax.swing.JFrame {

    private SimulatorItem si;
    private String[] computerList;
    private HostItem ci;
    private VConfComputer vConfComputer;

    /**
     * Creates new form VAddPackage
     */
    public VAddPackage() {
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }

    public VAddPackage(VConfComputer vConfComputer) {
        this.si = vConfComputer.getSI();
        this.ci = vConfComputer.getCI();
        this.vConfComputer = vConfComputer;
        List<Vertex<Node>> vhList = null;
        vhList = this.si.getSimulator().getRed().getAllHosts();
        computerList = new String[vhList.size()];
        int i = 0;
        for (Vertex<Node> vh : vhList) {
            computerList[i] = vh.getElement().getName();
            i++;
        }
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfPackage = new javax.swing.JLabel();
        txtTamañoPackage = new javax.swing.JTextField();
        jcbDestinoPackage = new javax.swing.JComboBox<>(this.computerList);
        lblKb = new javax.swing.JLabel();
        lblTamañoPackage = new javax.swing.JLabel();
        lblDestinoPackage = new javax.swing.JLabel();
        btnAceptarPackage = new javax.swing.JButton();
        btnCancelarPackage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configuracion del Paquete");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblConfPackage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfPackage.setText("Configuracion del Paquete");

        lblKb.setText("Kb");

        lblTamañoPackage.setText("Tamaño del Paquete");

        lblDestinoPackage.setText("Destino del Paquete");

        btnAceptarPackage.setText("Aceptar");
        btnAceptarPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPackageActionPerformed(evt);
            }
        });

        btnCancelarPackage.setText("Cancelar");
        btnCancelarPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPackageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfPackage)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptarPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamañoPackage)
                            .addComponent(lblDestinoPackage))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbDestinoPackage, 0, 107, Short.MAX_VALUE)
                            .addComponent(txtTamañoPackage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfPackage)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamañoPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKb)
                    .addComponent(lblTamañoPackage))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDestinoPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinoPackage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarPackage)
                    .addComponent(btnCancelarPackage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPackageActionPerformed
        this.setVisible(false);
        ci.getVertex()
                .getElement()
                .addPackage(new objects.Package(new BigDecimal(txtTamañoPackage
                                .getText()),
                                (Vertex<Node>) getChildItem(jcbDestinoPackage
                                        .getSelectedItem().toString())));
        this.vConfComputer.updateTComputer();
        this.vConfComputer.setEnabled(true);
        this.vConfComputer.getRemovePackage().setEnabled(true);
        this.vConfComputer.setVisible(true);
        this.vConfComputer.getBtnRemovePackage().setEnabled(true);
        /*table.removeAll();
				table.add(computerTable.getScrollPane());
				table.updateUI();
				jComputerConf.updateUI();
				jworkSpacePanel.updateUI();*/
    }//GEN-LAST:event_btnAceptarPackageActionPerformed

    private void btnCancelarPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPackageActionPerformed
        this.setVisible(false);
        this.vConfComputer.setEnabled(true);
        ci = new HostItem();
    }//GEN-LAST:event_btnCancelarPackageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAddPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAddPackage().setVisible(true);
            }
        });
    }

    private Vertex<Node> getChildItem(String selectedItem) {
        for (NodeItem hi : this.si.getWorkSpacePanel()
                .getChildsItems()) {
            if (hi.getVertex().getElement().getName()
                    .equalsIgnoreCase(selectedItem)) {
                return hi.getVertex();
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPackage;
    private javax.swing.JButton btnCancelarPackage;
    private javax.swing.JComboBox<String> jcbDestinoPackage;
    private javax.swing.JLabel lblConfPackage;
    private javax.swing.JLabel lblDestinoPackage;
    private javax.swing.JLabel lblKb;
    private javax.swing.JLabel lblTamañoPackage;
    private javax.swing.JTextField txtTamañoPackage;
    // End of variables declaration//GEN-END:variables
}
