/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;

import app.Elements.LinkerItem;
import app.Elements.RouterItem;
import app.Elements.SimulatorItem;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author alber
 */
public class VConfRouter extends javax.swing.JFrame {

    private SimulatorItem si;
    private VMain vMain;
    private RouterItem ri;

    /**
     * Creates new form VConfRouter
     */
    public VConfRouter() {
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }

    public VConfRouter(VMain vMain) {
        this.si = vMain.getSI();
        this.vMain = vMain;
        this.ri = new RouterItem(si,"");
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }
    public VConfRouter(RouterItem ri, VMain vMain) {
        this.si = vMain.getSI();
        this.vMain = vMain;
        initComponents();
        this.ri = ri;
        txtNameRouter.setText(ri.getName());
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfRouter = new javax.swing.JLabel();
        lblNameRouter = new javax.swing.JLabel();
        txtNameRouter = new javax.swing.JTextField();
        btnCancelarConfRouter = new javax.swing.JButton();
        btnAceptarConfRouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configuracion del Router");
        setResizable(false);

        lblConfRouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfRouter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfRouter.setText("Configuracion del Router");

        lblNameRouter.setText("Nombre del Router");

        btnCancelarConfRouter.setText("Cancelar");
        btnCancelarConfRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarConfRouterActionPerformed(evt);
            }
        });

        btnAceptarConfRouter.setText("Aceptar");
        btnAceptarConfRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarConfRouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfRouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblNameRouter)
                .addGap(32, 32, 32)
                .addComponent(txtNameRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(btnAceptarConfRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarConfRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfRouter)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameRouter)
                    .addComponent(txtNameRouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarConfRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarConfRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarConfRouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConfRouterActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarConfRouterActionPerformed

    private void btnAceptarConfRouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarConfRouterActionPerformed
        this.setVisible(false);
        this.vMain.setRouting(false);
        this.ri.getVertex().getElement().setName(txtNameRouter.getText());
        if(ri.getLocation().x == 0 && ri.getLocation().y == 0)
            ri.setBounds(150, 150, 120, 120);
        ri.getLblName().setText(txtNameRouter.getText());
        ri.setName(txtNameRouter.getText());
        JPopupMenu popUpMenuHost = new JPopupMenu();
        JMenuItem miConfigurar = new JMenuItem();
        miConfigurar.setText("Configurar Host");
        miConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VConfRouter vConfRouter = new VConfRouter(ri,vMain);
                vConfRouter.setVisible(true);
            }
        });
        popUpMenuHost.add(miConfigurar);
        JMenuItem miEliminar = new JMenuItem();
        miEliminar.setText("Eliminar Host");
        miEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si.getWorkSpacePanel().remove(ri.getLblName());
                si.getWorkSpacePanel().remove(ri);
                si.getSimulator().getRed().removeHost(ri.getVertex());
                si.getWorkSpacePanel().updateUI();
                vMain.setRouting(false);
                for(LinkerItem li : ri.getLinkers()){
                    boolean borrado = si.getWorkSpacePanel().getLinkers().remove(li);
                    if(borrado)
                        si.getWorkSpacePanel().remove(li.getLblName());
                } 
                si.getWorkSpacePanel().getChildsItems().remove(ri);
                enabledBotons();
            }
        });
        popUpMenuHost.add(miEliminar);
        ri.setComponentPopupMenu(popUpMenuHost);
        if(!si.getWorkSpacePanel().getChildsItems().contains(ri))
            si.getWorkSpacePanel().add(ri);
        enabledBotons();

        //si.getWorkSpacePanel().getChildsItems().add(ri);
        
        si.getWorkSpacePanel().updateUI();
    }//GEN-LAST:event_btnAceptarConfRouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VConfRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VConfRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VConfRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VConfRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VConfRouter().setVisible(true);
            }
        });
    }
    public void enabledBotons() {
        if (si.getWorkSpacePanel().getChildsItems().size() >= 2) {
            this.vMain.getBtnNewLinker().setEnabled(true);
        } else {
            this.vMain.getBtnNewLinker().setEnabled(false);
        }
        if (si.getWorkSpacePanel().getChildsItems().size() > 0 && si.getWorkSpacePanel().getLinkers().size() >= si.getWorkSpacePanel().getChildsItems().size() - 1) {
            this.vMain.getBtnStart().setEnabled(true);
        } else {
            this.vMain.getBtnStart().setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarConfRouter;
    private javax.swing.JButton btnCancelarConfRouter;
    private javax.swing.JLabel lblConfRouter;
    private javax.swing.JLabel lblNameRouter;
    private javax.swing.JTextField txtNameRouter;
    // End of variables declaration//GEN-END:variables
}
