
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;

import app.Elements.SimulatorItem;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import material.graphs.Edge;
import material.graphs.Vertex;
import objects.Linker;
import objects.Router;
import objects.Node;
import app.Elements.NodeItem;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class VEnrutamiento extends javax.swing.JFrame {

    private SimulatorItem si;
    private VMain vMain;
    private VTraceStepByStep vTraceStepByStep;
    private String[] linkers;
    private boolean anyRandom;

    /**
     * Creates new form VEnrutamiento
     */
    public VEnrutamiento() {
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2,
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }

    public VEnrutamiento(VMain vMain,boolean anyRandom, boolean routing) {
        this.si = vMain.getSI();
        this.vMain = vMain;
        this.anyRandom = anyRandom;
        String[] linkers = new String[si.getSimulator().getRed().getRed().edges()
                .size()];
        int i = 0;
        for (Edge<objects.Linker> eL : si.getSimulator().getRed().getRed().edges()) {
            linkers[i] = eL.getElement().getIp();
            i++;
        }
        this.linkers = linkers;
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2,
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);  
        this.btnStartToFinish.setEnabled(!anyRandom);
        if(routing){
            for(int j = 1; j <= si.getSimulator().getRed().getAllRouters().size(); j++){
            Vertex<Node> vr = getChildItem(jtHostTable.getColumnName(j).toString());
            Router r = (Router) vr.getElement();
                for(int m = 0; m < si.getSimulator().getRed().getAllHosts().size(); m++){
                    Vertex<Node> vh = getChildItem(jtHostTable.getValueAt(m, 0).toString());
                    String ip = r.getEnrutamiento(vh).getElement().getIp();
                    if(ip != null)
                        jtHostTable.setValueAt(ip, m, j);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jConfTablaEnrutamiento = new javax.swing.JPanel();
        lblConfTablaEnrutamiento = new javax.swing.JLabel();
        tbRun = new javax.swing.JToolBar();
        btnStart = new javax.swing.JButton();
        btnStartToFinish = new javax.swing.JButton();
        btnEnrutadoAutomatico = new javax.swing.JButton();
        jSPHostTable = new javax.swing.JScrollPane();
        jtHostTable = new javax.swing.JTable();

        lblConfTablaEnrutamiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfTablaEnrutamiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfTablaEnrutamiento.setText("Configurar Tabla de Enrutamiento");

        tbRun.setFloatable(false);
        tbRun.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbRun.setRollover(true);

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconStart2.png"))); // NOI18N
        btnStart.setFocusable(false);
        btnStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStart.setMargin(new java.awt.Insets(20, 14, 20, 14));
        btnStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        tbRun.add(btnStart);

        btnStartToFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconStartToFinish2.png"))); // NOI18N
        btnStartToFinish.setToolTipText("");
        btnStartToFinish.setFocusable(false);
        btnStartToFinish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStartToFinish.setMargin(new java.awt.Insets(20, 14, 20, 14));
        btnStartToFinish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStartToFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartToFinishActionPerformed(evt);
            }
        });
        tbRun.add(btnStartToFinish);

        btnEnrutadoAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/routingIcon.png"))); // NOI18N
        btnEnrutadoAutomatico.setToolTipText("");
        btnEnrutadoAutomatico.setFocusable(false);
        btnEnrutadoAutomatico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnrutadoAutomatico.setMargin(new java.awt.Insets(20, 14, 20, 14));
        btnEnrutadoAutomatico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnrutadoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrutadoAutomaticoActionPerformed(evt);
            }
        });
        tbRun.add(btnEnrutadoAutomatico);

        List<Vertex<objects.Node>> vhListComputers = this.si.getSimulator().getRed()
        .getAllHosts();
        List<Vertex<objects.Node>> vhListRouters = this.si.getSimulator().getRed()
        .getAllRouters();

        Object[][] rowData = new Object[vhListComputers.size()][vhListRouters.size() + 1];
        String[] columnNames = new String[vhListRouters.size() + 1];
        columnNames[0] = "Hosts";
        int i = 0;
        int j = 1;

        for (Vertex<objects.Node> vHC : vhListComputers) {
            rowData[i][0] = vHC.getElement().getName();
            for (Vertex<objects.Node> vHR : vhListRouters) {
                columnNames[j] = vHR.getElement().getName();
                j++;
            }
            j = 1;
            i++;
        }
        jtHostTable.setModel(new javax.swing.table.DefaultTableModel(
            rowData,
            columnNames
        ));
        for(int m = 1; m <= vhListRouters.size(); m++){
            JComboBox<String> comboBox = new JComboBox<>(this.linkers);
            TableColumn column = jtHostTable.getColumnModel().getColumn(m);
            column.setCellEditor(new DefaultCellEditor(comboBox));
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setToolTipText("Click for combo box");
            column.setCellRenderer(renderer);
        }
        jSPHostTable.setViewportView(jtHostTable);

        javax.swing.GroupLayout jConfTablaEnrutamientoLayout = new javax.swing.GroupLayout(jConfTablaEnrutamiento);
        jConfTablaEnrutamiento.setLayout(jConfTablaEnrutamientoLayout);
        jConfTablaEnrutamientoLayout.setHorizontalGroup(
            jConfTablaEnrutamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfTablaEnrutamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbRun, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPHostTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(71, 71, 71))
            .addGroup(jConfTablaEnrutamientoLayout.createSequentialGroup()
                .addComponent(lblConfTablaEnrutamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jConfTablaEnrutamientoLayout.setVerticalGroup(
            jConfTablaEnrutamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfTablaEnrutamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfTablaEnrutamiento)
                .addGroup(jConfTablaEnrutamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jConfTablaEnrutamientoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPHostTable, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jConfTablaEnrutamientoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tbRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jConfTablaEnrutamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jConfTablaEnrutamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartToFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartToFinishActionPerformed
        boolean allEnrutado = true;
        for (int i = 0; i < si.getSimulator().getRed().getAllHosts().size(); i++) {
            for (int j = 1; j <= si.getSimulator().getRed().getAllRouters().size(); j++) {
                if(jtHostTable.getValueAt(i, j) == null)
                    allEnrutado = false;  
            }
        }
        if(allEnrutado){
            this.vMain.setRouting(true);
            for (int i = 0; i < si.getSimulator().getRed().getAllHosts().size(); i++) {
                Vertex<Node> vc = getChildItem(jtHostTable.getValueAt(i, 0).toString());
                for (int j = 1; j <= si.getSimulator().getRed().getAllRouters().size(); j++) {
                    Router r = (Router) getChildItem(jtHostTable.getColumnName(j).toString()).getElement();
                    r.enrutar(vc, getLinkerItem((String) jtHostTable.getValueAt(i, j)));
                }
            }
            this.setVisible(false);
            List<simulator.Event> trace = si
                    .getSimulator().play();
            this.setVisible(false);
            this.vTraceStepByStep = new VTraceStepByStep(this.si,trace);
            vTraceStepByStep.setVisible(true);
            vTraceStepByStep.getjToolBarTrace().setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this,"Se necesitan enrutar todos los routers para ejecutar","Enruta todos los routers",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStartToFinishActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        boolean allEnrutado = true;
        for (int i = 0; i < si.getSimulator().getRed().getAllHosts().size(); i++) {
            for (int j = 1; j <= si.getSimulator().getRed().getAllRouters().size(); j++) {
                if(jtHostTable.getValueAt(i, j) == null)
                    allEnrutado = false;  
            }
        }
        if(allEnrutado){
            this.vMain.setRouting(true);
            for (int i = 0; i < si.getSimulator().getRed().getAllHosts().size(); i++) {
                Vertex<Node> vc = getChildItem(jtHostTable.getValueAt(i, 0).toString());
                for (int j = 1; j <= si.getSimulator().getRed().getAllRouters().size(); j++) {
                    Router r = (Router) getChildItem(jtHostTable.getColumnName(j).toString()).getElement();
                    r.enrutar(vc, getLinkerItem((String) jtHostTable.getValueAt(i, j)));
                }
            }
            this.setVisible(false);
            this.vTraceStepByStep = new VTraceStepByStep(this.si);
            vTraceStepByStep.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Se necesitan enrutar todos los routers para ejecutar","Enrutar routers",JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEnrutadoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrutadoAutomaticoActionPerformed
        for(int j = 1; j <= si.getSimulator().getRed().getAllRouters().size(); j++){
            Vertex<Node> vr = getChildItem(jtHostTable.getColumnName(j).toString());
            for(int i = 0; i < si.getSimulator().getRed().getAllHosts().size(); i++){
                Vertex<Node> vh = getChildItem(jtHostTable.getValueAt(i, 0).toString());
                Edge<Linker> linker = this.si.getSimulator().getRed().getEnrutamiento(vh,vr);
                jtHostTable.setValueAt(linker.getElement().getIp(), i, j);
            }
        }
    }//GEN-LAST:event_btnEnrutadoAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEnrutamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEnrutamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEnrutamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEnrutamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEnrutamiento().setVisible(true);
            }
        });
    }

    private Vertex<Node> getChildItem(String selectedItem) {
        for (NodeItem hi : this.si.getWorkSpacePanel()
                .getChildsItems()) {
            if (hi.getVertex().getElement().getName()
                    .equalsIgnoreCase(selectedItem)) {
                return hi.getVertex();
            }
        }
        return null;
    }

    private Edge<Linker> getLinkerItem(String selectedItem) {
        for (Edge<Linker> el : this.si.getSimulator().getRed().getRed().edges()) {
            if (el.getElement().getIp().equalsIgnoreCase(selectedItem)) {
                return el;
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrutadoAutomatico;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStartToFinish;
    private javax.swing.JPanel jConfTablaEnrutamiento;
    private javax.swing.JScrollPane jSPHostTable;
    private javax.swing.JTable jtHostTable;
    private javax.swing.JLabel lblConfTablaEnrutamiento;
    private javax.swing.JToolBar tbRun;
    // End of variables declaration//GEN-END:variables
}
