/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;

/**
 *
 * @author alber
 */
public class VNameFile extends javax.swing.JFrame {

    private VMain vMain;

    /**
     * Creates new form VNameFile
     */
    public VNameFile() {
        initComponents();
    }

    public VNameFile(VMain vMain) {
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2,
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
        this.vMain = vMain;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameFile = new javax.swing.JPanel();
        lblNameFile = new javax.swing.JLabel();
        lblNombreFichero = new javax.swing.JLabel();
        txtNameFile = new javax.swing.JTextField();
        btnAceptarNameFile = new javax.swing.JButton();
        btnCancelarNameFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Guardar Archivo");
        setResizable(false);

        lblNameFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameFile.setText("Escribe el nombre del Archivo");

        lblNombreFichero.setText("Nombre del Fichero");

        btnAceptarNameFile.setText("Aceptar");
        btnAceptarNameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNameFileActionPerformed(evt);
            }
        });

        btnCancelarNameFile.setText("Cancelar");
        btnCancelarNameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNameFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jNameFileLayout = new javax.swing.GroupLayout(jNameFile);
        jNameFile.setLayout(jNameFileLayout);
        jNameFileLayout.setHorizontalGroup(
            jNameFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNameFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jNameFileLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jNameFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNameFileLayout.createSequentialGroup()
                        .addComponent(btnAceptarNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jNameFileLayout.createSequentialGroup()
                        .addComponent(lblNombreFichero)
                        .addGap(28, 28, 28)
                        .addComponent(txtNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jNameFileLayout.setVerticalGroup(
            jNameFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNameFileLayout.createSequentialGroup()
                .addComponent(lblNameFile)
                .addGap(18, 18, 18)
                .addGroup(jNameFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFichero)
                    .addComponent(txtNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jNameFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jNameFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jNameFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarNameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNameFileActionPerformed
        vMain.setNameFile(txtNameFile.getText());
        this.setVisible(false);
        JFileChooser jd = new JFileChooser();
        //jd.showOpenDialog(this);
        jd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jd.setAcceptAllFileFilterUsed(false);
        if (jd.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            try {
                if (txtNameFile.getText() != null) {
                    FileOutputStream fileOut = new FileOutputStream(jd.getSelectedFile().getAbsolutePath() +"//" + vMain.getNameFile());
                    ObjectOutputStream objectOut = new ObjectOutputStream(fileOut);
                    objectOut.writeObject(vMain.getSI().toString());
                    objectOut.close();
                    System.out.println("The Object  was succesfully written to a file");
                } else {

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAceptarNameFileActionPerformed

    private void btnCancelarNameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNameFileActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarNameFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNameFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarNameFile;
    private javax.swing.JButton btnCancelarNameFile;
    private javax.swing.JPanel jNameFile;
    private javax.swing.JLabel lblNameFile;
    private javax.swing.JLabel lblNombreFichero;
    private javax.swing.JTextField txtNameFile;
    // End of variables declaration//GEN-END:variables
}
