/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;

import app.Elements.HostItem;
import java.math.BigDecimal;
import objects.Host;

/**
 *
 * @author alber
 */
public class VRandomSend extends javax.swing.JFrame {

    private VConfComputer vConfComputer;

    /**
     * Creates new form VRandomSend
     */
    public VRandomSend() {
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }

    public VRandomSend(VConfComputer vConfComputer) {
        this.vConfComputer = vConfComputer;
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }
     public VRandomSend(VConfComputer vConfComputer, Host c) {
        this.vConfComputer = vConfComputer;
        initComponents();
        this.txtTamañoMedioRandomSend.setText(c.getRandomSend().getSizePackage().toString());
        this.txtTiempoMedioMedioRandomSend.setText(c.getRandomSend().getAverageTime().toString());
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnvioAleatorio = new javax.swing.JLabel();
        lblTamañoPackageRandomSend = new javax.swing.JLabel();
        lblTiempoMedioRandomSend = new javax.swing.JLabel();
        txtTamañoMedioRandomSend = new javax.swing.JTextField();
        txtTiempoMedioMedioRandomSend = new javax.swing.JTextField();
        btnCancelarRandomSend = new javax.swing.JButton();
        btnAceptarRandomSend = new javax.swing.JButton();
        lblKbRandomSend = new javax.swing.JLabel();
        lblSegundosRandomSend = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("app/Windows/Bundle"); // NOI18N
        setTitle(bundle.getString("VRandomSend.title")); // NOI18N
        setResizable(false);

        lblEnvioAleatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEnvioAleatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnvioAleatorio.setText(bundle.getString("VRandomSend.lblEnvioAleatorio.text")); // NOI18N

        lblTamañoPackageRandomSend.setText(bundle.getString("VRandomSend.lblTamañoPackageRandomSend.text")); // NOI18N

        lblTiempoMedioRandomSend.setText(bundle.getString("VRandomSend.lblTiempoMedioRandomSend.text")); // NOI18N

        btnCancelarRandomSend.setText(bundle.getString("VRandomSend.btnCancelarRandomSend.text")); // NOI18N
        btnCancelarRandomSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRandomSendActionPerformed(evt);
            }
        });

        btnAceptarRandomSend.setText(bundle.getString("VRandomSend.btnAceptarRandomSend.text")); // NOI18N
        btnAceptarRandomSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRandomSendActionPerformed(evt);
            }
        });

        lblKbRandomSend.setText(bundle.getString("VRandomSend.lblKbRandomSend.text")); // NOI18N

        lblSegundosRandomSend.setText(bundle.getString("VRandomSend.lblSegundosRandomSend.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEnvioAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnCancelarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTiempoMedioRandomSend)
                                    .addComponent(lblTamañoPackageRandomSend))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTamañoMedioRandomSend)
                                    .addComponent(txtTiempoMedioMedioRandomSend))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKbRandomSend)
                                    .addComponent(lblSegundosRandomSend))))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnvioAleatorio)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamañoPackageRandomSend)
                    .addComponent(txtTamañoMedioRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKbRandomSend))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoMedioRandomSend)
                    .addComponent(txtTiempoMedioMedioRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegundosRandomSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarRandomSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRandomSendActionPerformed
        this.setVisible(false);
        if (vConfComputer.getCI().getVertex().getElement() instanceof Host) {
            Host computer = (Host) vConfComputer.getCI().getVertex()
                    .getElement();
            computer.setRandomSend(null);

        }
        vConfComputer.setEnabled(true);
        vConfComputer.getRbtnEnvioAleatorio().setSelected(false);
        vConfComputer.getAddPackage().setVisible(true);
        vConfComputer.getRemovePackage().setVisible(true);
        vConfComputer.getComputerTable().setVisible(true);
        vConfComputer.setVisible(true);
    }//GEN-LAST:event_btnCancelarRandomSendActionPerformed

    private void btnAceptarRandomSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRandomSendActionPerformed
        HostItem ci = this.vConfComputer.getCI();
        if (ci.getVertex().getElement() instanceof Host) {
            Host computer = (Host) ci.getVertex()
                    .getElement();
            computer.setRandomSend(
                    new BigDecimal(txtTamañoMedioRandomSend.getText()),
                    new BigDecimal(txtTiempoMedioMedioRandomSend.getText()));
        }
        this.setVisible(false);
        vConfComputer.setEnabled(true);
        vConfComputer.setVisible(true);
    }//GEN-LAST:event_btnAceptarRandomSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRandomSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRandomSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRandomSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRandomSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRandomSend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRandomSend;
    private javax.swing.JButton btnCancelarRandomSend;
    private javax.swing.JLabel lblEnvioAleatorio;
    private javax.swing.JLabel lblKbRandomSend;
    private javax.swing.JLabel lblSegundosRandomSend;
    private javax.swing.JLabel lblTamañoPackageRandomSend;
    private javax.swing.JLabel lblTiempoMedioRandomSend;
    private javax.swing.JTextField txtTamañoMedioRandomSend;
    private javax.swing.JTextField txtTiempoMedioMedioRandomSend;
    // End of variables declaration//GEN-END:variables
}
