/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;

import app.Elements.HostItem;
import app.Elements.NodeItem;
import java.math.BigDecimal;
import objects.Host;

/**
 *
 * @author alber
 */
public class VRandomSend extends javax.swing.JFrame {

    private VConfHost vConfComputer;

    /**
     * Creates new form VRandomSend
     */
    public VRandomSend() {
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }

    public VRandomSend(VConfHost vConfComputer) {
        this.vConfComputer = vConfComputer;
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }
     public VRandomSend(VConfHost vConfComputer, Host c) {
        this.vConfComputer = vConfComputer;
        initComponents();
        configComponents(c);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTamanioPackageRandomSend = new javax.swing.JLabel();
        lblTiempoMedioRandomSend = new javax.swing.JLabel();
        txtTamanioMedioRandomSend = new javax.swing.JTextField();
        txtTiempoMedioMedioRandomSend = new javax.swing.JTextField();
        btnCancelarRandomSend = new javax.swing.JButton();
        btnAceptarRandomSend = new javax.swing.JButton();
        lblKbRandomSend = new javax.swing.JLabel();
        lblSegundosRandomSend = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("app/Windows/Bundle"); // NOI18N
        setTitle(bundle.getString("VRandomSend.title")); // NOI18N
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(399, 113));
        setResizable(false);

        lblTamanioPackageRandomSend.setText(bundle.getString("VRandomSend.lblTamanioPackageRandomSend.text")); // NOI18N

        lblTiempoMedioRandomSend.setText(bundle.getString("VRandomSend.lblTiempoMedioRandomSend.text")); // NOI18N

        txtTamanioMedioRandomSend.setToolTipText(bundle.getString("VRandomSend.txtTamanioMedioRandomSend.toolTipText")); // NOI18N

        txtTiempoMedioMedioRandomSend.setToolTipText(bundle.getString("VRandomSend.txtTiempoMedioMedioRandomSend.toolTipText")); // NOI18N

        btnCancelarRandomSend.setText(bundle.getString("VRandomSend.btnCancelarRandomSend.text")); // NOI18N
        btnCancelarRandomSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRandomSendActionPerformed(evt);
            }
        });

        btnAceptarRandomSend.setText(bundle.getString("VRandomSend.btnAceptarRandomSend.text")); // NOI18N
        btnAceptarRandomSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRandomSendActionPerformed(evt);
            }
        });

        lblKbRandomSend.setText(bundle.getString("VRandomSend.lblKbRandomSend.text")); // NOI18N

        lblSegundosRandomSend.setText(bundle.getString("VRandomSend.lblSegundosRandomSend.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addComponent(btnAceptarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamanioPackageRandomSend)
                            .addComponent(lblTiempoMedioRandomSend))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTamanioMedioRandomSend)
                            .addComponent(txtTiempoMedioMedioRandomSend))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKbRandomSend)
                            .addComponent(lblSegundosRandomSend))))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanioPackageRandomSend)
                    .addComponent(txtTamanioMedioRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKbRandomSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoMedioRandomSend)
                    .addComponent(txtTiempoMedioMedioRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegundosRandomSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarRandomSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarRandomSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRandomSendActionPerformed
        this.setVisible(false);
        if (vConfComputer.getCI().getVertex().getElement() instanceof Host) {
            Host computer = (Host) vConfComputer.getCI().getVertex()
                    .getElement();
            computer.setRandomSend(null);
            vConfComputer.getSI().getvMain().setanyRandom(anyRandom());
        }
        vConfComputer.setEnabled(true);
        vConfComputer.getRbtnEnvioAleatorio().setSelected(false);
        vConfComputer.getAddPackage().setVisible(true);
        vConfComputer.getRemovePackage().setVisible(true);
        vConfComputer.getComputerTable().setVisible(true);
        vConfComputer.setVisible(true);
    }//GEN-LAST:event_btnCancelarRandomSendActionPerformed

    private void btnAceptarRandomSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRandomSendActionPerformed
        HostItem ci = this.vConfComputer.getCI();
        if (ci.getVertex().getElement() instanceof Host) {
            Host computer = (Host) ci.getVertex()
                    .getElement();
            computer.setRandomSend(
                    new BigDecimal(txtTamanioMedioRandomSend.getText()),
                    new BigDecimal(txtTiempoMedioMedioRandomSend.getText()));
            vConfComputer.getSI().getvMain().setanyRandom(true);
        }
        this.setVisible(false);
        vConfComputer.setEnabled(true);
        vConfComputer.setVisible(true);
    }//GEN-LAST:event_btnAceptarRandomSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRandomSend;
    private javax.swing.JButton btnCancelarRandomSend;
    private javax.swing.JLabel lblKbRandomSend;
    private javax.swing.JLabel lblSegundosRandomSend;
    private javax.swing.JLabel lblTamanioPackageRandomSend;
    private javax.swing.JLabel lblTiempoMedioRandomSend;
    private javax.swing.JTextField txtTamanioMedioRandomSend;
    private javax.swing.JTextField txtTiempoMedioMedioRandomSend;
    // End of variables declaration//GEN-END:variables

    private void configComponents(Host c) {
        this.txtTamanioMedioRandomSend.setText(c.getRandomSend().getSizePackage().toString());
        this.txtTiempoMedioMedioRandomSend.setText(c.getRandomSend().getAverageTime().toString());
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2, 
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }
    private boolean anyRandom() {
        for(NodeItem ni : vConfComputer.getSI().getWorkSpacePanel().getChildsItems()){
            if(ni.getVertex().getElement() instanceof Host){
                Host h =  (Host) ni.getVertex().getElement();
                if(h.isRandomSend()){
                    return true;
                }
            }
        }
        return false;
    }
}
