/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Windows;

import app.Elements.SimulatorItem;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JToolBar;
import javax.swing.table.DefaultTableModel;
import simulator.Event;

/**
 *
 * @author alber
 */
public class VTraceStepByStep extends javax.swing.JFrame {
    private SimulatorItem si;
    private List<Event> eventos;
    private int contRow;
    private int i = 0;
    /**
     * Creates new form VTraceStepByStep
     */
    public VTraceStepByStep() {
        initComponents();
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2,
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }

    public VTraceStepByStep(SimulatorItem si) {
        this.si = si;
        this.eventos = new ArrayList<>();
        this.contRow = 0;
        initComponents();
        btnPlayUntil.setEnabled(false);
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2,
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
    }
    public VTraceStepByStep(SimulatorItem si,List<Event> eventos) {
        this.si = si;
        this.eventos = new ArrayList<>();
        this.contRow = 0;
        initComponents();
        btnPlayUntil.setEnabled(false);
        setLocation((getToolkit().getScreenSize().width - this.getWidth()) / 2,
                (getToolkit().getScreenSize().height - this.getHeight()) / 2);
        DefaultTableModel model = (DefaultTableModel) jTEvents.getModel();
        for(Event e : eventos){
            model.addRow(new Object[]{e.getTime(),e.getMensaje()});
        }
        this.btnNextTrace.setVisible(false);
        jTEvents.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTrace = new javax.swing.JPanel();
        jTableTrace = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEvents = new javax.swing.JTable();
        jToolBarTrace = new javax.swing.JToolBar();
        btnNextTrace = new javax.swing.JButton();
        btnPlayUntil = new javax.swing.JButton();
        txtTime = new javax.swing.JTextField();

        setTitle("Traza de la Ejecucion");

        jTEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tiempo", "Eventos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTEvents.getColumnModel().getColumn(0).setPreferredWidth(10);
        jScrollPane1.setViewportView(jTEvents);
        if (jTEvents.getColumnModel().getColumnCount() > 0) {
            jTEvents.getColumnModel().getColumn(0).setResizable(false);
            jTEvents.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jTableTraceLayout = new javax.swing.GroupLayout(jTableTrace);
        jTableTrace.setLayout(jTableTraceLayout);
        jTableTraceLayout.setHorizontalGroup(
            jTableTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
            .addGroup(jTableTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTableTraceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jTableTraceLayout.setVerticalGroup(
            jTableTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
            .addGroup(jTableTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTableTraceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jToolBarTrace.setBorder(null);
        jToolBarTrace.setFloatable(false);
        jToolBarTrace.setRollover(true);
        jToolBarTrace.setToolTipText("Next Step");

        btnNextTrace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nextIcon2.png"))); // NOI18N
        btnNextTrace.setToolTipText("Siguiente Evento");
        btnNextTrace.setFocusable(false);
        btnNextTrace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNextTrace.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnNextTrace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNextTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextTraceActionPerformed(evt);
            }
        });
        jToolBarTrace.add(btnNextTrace);

        btnPlayUntil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconStartToFinish2.png"))); // NOI18N
        btnPlayUntil.setFocusable(false);
        btnPlayUntil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayUntil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayUntil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayUntilActionPerformed(evt);
            }
        });
        jToolBarTrace.add(btnPlayUntil);

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        jToolBarTrace.add(txtTime);

        javax.swing.GroupLayout jTraceLayout = new javax.swing.GroupLayout(jTrace);
        jTrace.setLayout(jTraceLayout);
        jTraceLayout.setHorizontalGroup(
            jTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTraceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTableTrace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTraceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToolBarTrace, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jTraceLayout.setVerticalGroup(
            jTraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTraceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarTrace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTableTrace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTrace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTrace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextTraceActionPerformed
        List<Event> ev = this.si.getSimulator().playOneStep(i);
        eventos.addAll(ev);
        eventos.sort(new Event());
        i++;
        if(!eventos.isEmpty()){
            Event e = eventos.remove(0);
            DefaultTableModel model = (DefaultTableModel) jTEvents.getModel();
            model.addRow(new Object[]{e.getTime(),e.getMensaje()});
            jTEvents.updateUI();
        }else
            btnNextTrace.setEnabled(false);
    }//GEN-LAST:event_btnNextTraceActionPerformed

    private void btnPlayUntilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayUntilActionPerformed
        BigDecimal time = new BigDecimal(txtTime.getText());
        List<Event> ev = this.si.getSimulator().play(time);
    }//GEN-LAST:event_btnPlayUntilActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        if(txtTime.getText() != null && txtTime.getText() != ""){
            btnPlayUntil.setEnabled(true);
        }else
            btnPlayUntil.setEnabled(false);
    }//GEN-LAST:event_txtTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VTraceStepByStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VTraceStepByStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VTraceStepByStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VTraceStepByStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VTraceStepByStep().setVisible(true);
            }
        });
    }

    public JToolBar getjToolBarTrace() {
        return jToolBarTrace;
    }

    public void setjToolBarTrace(JToolBar jToolBarTrace) {
        this.jToolBarTrace = jToolBarTrace;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextTrace;
    private javax.swing.JButton btnPlayUntil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTEvents;
    private javax.swing.JPanel jTableTrace;
    private javax.swing.JToolBar jToolBarTrace;
    private javax.swing.JPanel jTrace;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
